language: c
sudo: required
dist: trusty
compiler: gcc

# safelist
branches:
  only:
  - master
  - libreswitch
  - /^release.*$/

env:
- PLATFORM=appliance
- PLATFORM=genericx86-64

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq gawk wget git-core diffstat unzip texinfo build-essential chrpath screen curl device-tree-compiler

install: true

script:
- make configure $PLATFORM
- make
